import type { Country, PricingTier, Testimonial, FAQ } from './types'

export const countries: Country[] = [
  {
    id: '1',
    name: 'United States',
    slug: 'usa',
    flag: '🇺🇸',
    region: 'Americas',
    investmentRating: 4.5,
    investmentCategory: 'Growth',
    rentalYield: 4.2,
    capitalAppreciation5Y: 8.5,
    priceToRentRatio: 23.8,
    transactionCosts: 3.5,
    propertyTaxRate: 1.1,
    rentalIncomeTax: 30,
    gdpGrowth: 2.5,
    inflationRate: 3.2,
    currencyStability: 0.95,
    populationGrowth: 0.5,
    mortgageAvailability: 'High',
    foreignOwnershipRestrictions: 'None',
    managementFees: 8,
    maintenanceCosts: 1.5,
    insuranceCosts: 0.8,
    executiveSummary: 'The United States offers diverse investment opportunities across major metropolitan areas. With strong legal protections for property owners, high liquidity, and consistent capital appreciation in key markets like Austin, Miami, and Nashville, the US remains a cornerstone for international real estate portfolios.',
    badges: ['Best Growth', 'Best Overall'],
  },
  {
    id: '2',
    name: 'Spain',
    slug: 'spain',
    flag: '🇪🇸',
    region: 'Europe',
    investmentRating: 4.2,
    investmentCategory: 'Balanced',
    rentalYield: 3.8,
    capitalAppreciation5Y: 2.5,
    priceToRentRatio: 26.3,
    transactionCosts: 7.5,
    propertyTaxRate: 0.4,
    rentalIncomeTax: 19,
    gdpGrowth: 2.8,
    inflationRate: 2.1,
    currencyStability: 0.85,
    populationGrowth: 0.3,
    mortgageAvailability: 'Medium',
    foreignOwnershipRestrictions: 'Low',
    managementFees: 10,
    maintenanceCosts: 1.2,
    insuranceCosts: 0.5,
    executiveSummary: 'Spain combines lifestyle appeal with solid investment fundamentals. Coastal regions and major cities like Madrid and Barcelona offer strong rental demand from both tourists and expats. The Golden Visa program adds additional appeal for non-EU investors seeking residency.',
    badges: ['Best for Beginners'],
  },
  {
    id: '3',
    name: 'Italy',
    slug: 'italy',
    flag: '🇮🇹',
    region: 'Europe',
    investmentRating: 3.8,
    investmentCategory: 'Balanced',
    rentalYield: 3.2,
    capitalAppreciation5Y: 1.8,
    priceToRentRatio: 31.2,
    transactionCosts: 10.0,
    propertyTaxRate: 0.76,
    rentalIncomeTax: 21,
    gdpGrowth: 1.5,
    inflationRate: 2.4,
    currencyStability: 0.85,
    populationGrowth: -0.2,
    mortgageAvailability: 'Medium',
    foreignOwnershipRestrictions: 'Low',
    managementFees: 12,
    maintenanceCosts: 1.5,
    insuranceCosts: 0.6,
    executiveSummary: 'Italy offers unique opportunities in historic properties and tourism-driven markets. While yields are moderate, the cultural appeal of Tuscany, Amalfi Coast, and Milan provides consistent demand. The €1 house program in rural areas has created niche renovation opportunities.',
    badges: [],
  },
  {
    id: '4',
    name: 'United Kingdom',
    slug: 'uk',
    flag: '🇬🇧',
    region: 'Europe',
    investmentRating: 4.0,
    investmentCategory: 'Balanced',
    rentalYield: 3.5,
    capitalAppreciation5Y: 3.2,
    priceToRentRatio: 28.5,
    transactionCosts: 5.0,
    propertyTaxRate: 0.5,
    rentalIncomeTax: 20,
    gdpGrowth: 1.8,
    inflationRate: 3.5,
    currencyStability: 0.80,
    populationGrowth: 0.4,
    mortgageAvailability: 'High',
    foreignOwnershipRestrictions: 'None',
    managementFees: 10,
    maintenanceCosts: 1.3,
    insuranceCosts: 0.4,
    executiveSummary: 'The UK property market remains resilient despite Brexit challenges. London continues as a global financial hub with premium pricing, while Manchester, Birmingham, and Leeds offer higher yields. Strong tenant protections and transparent legal framework provide security for investors.',
    badges: [],
  },
  {
    id: '5',
    name: 'United Arab Emirates',
    slug: 'uae',
    flag: '🇦🇪',
    region: 'Middle East',
    investmentRating: 4.6,
    investmentCategory: 'High Yield',
    rentalYield: 6.5,
    capitalAppreciation5Y: 5.8,
    priceToRentRatio: 15.4,
    transactionCosts: 4.0,
    propertyTaxRate: 0,
    rentalIncomeTax: 0,
    gdpGrowth: 4.2,
    inflationRate: 2.8,
    currencyStability: 0.90,
    populationGrowth: 1.2,
    mortgageAvailability: 'High',
    foreignOwnershipRestrictions: 'Low',
    managementFees: 5,
    maintenanceCosts: 1.0,
    insuranceCosts: 0.3,
    executiveSummary: 'The UAE, particularly Dubai and Abu Dhabi, offers tax-free rental income and strong capital growth. Freehold zones allow foreign ownership, and the Golden Visa program provides long-term residency. High expatriate population ensures consistent rental demand.',
    badges: ['Best Rental Yield', 'Most Tax Efficient'],
  },
  {
    id: '6',
    name: 'Portugal',
    slug: 'portugal',
    flag: '🇵🇹',
    region: 'Europe',
    investmentRating: 4.3,
    investmentCategory: 'Tax Efficient',
    rentalYield: 4.5,
    capitalAppreciation5Y: 6.2,
    priceToRentRatio: 22.2,
    transactionCosts: 6.5,
    propertyTaxRate: 0.3,
    rentalIncomeTax: 25,
    gdpGrowth: 2.3,
    inflationRate: 2.0,
    currencyStability: 0.85,
    populationGrowth: 0.1,
    mortgageAvailability: 'Medium',
    foreignOwnershipRestrictions: 'None',
    managementFees: 8,
    maintenanceCosts: 1.0,
    insuranceCosts: 0.4,
    executiveSummary: 'Portugal has emerged as a top European investment destination. Lisbon and Porto offer strong appreciation, while the Algarve provides tourism-driven yields. The Non-Habitual Resident tax regime offers significant benefits for retirees and remote workers.',
    badges: ['Best for Beginners'],
  },
  {
    id: '7',
    name: 'Singapore',
    slug: 'singapore',
    flag: '🇸🇬',
    region: 'Asia',
    investmentRating: 4.4,
    investmentCategory: 'Growth',
    rentalYield: 2.8,
    capitalAppreciation5Y: 9.2,
    priceToRentRatio: 35.7,
    transactionCosts: 8.0,
    propertyTaxRate: 0.4,
    rentalIncomeTax: 22,
    gdpGrowth: 3.5,
    inflationRate: 2.5,
    currencyStability: 0.92,
    populationGrowth: 0.8,
    mortgageAvailability: 'High',
    foreignOwnershipRestrictions: 'Moderate',
    managementFees: 6,
    maintenanceCosts: 0.8,
    insuranceCosts: 0.2,
    executiveSummary: 'Singapore is Asia\'s premier property market with exceptional stability and governance. While entry costs are high (Additional Buyer Stamp Duty for foreigners), the market offers security, liquidity, and consistent long-term appreciation.',
    badges: ['Best Growth'],
  },
  {
    id: '8',
    name: 'Thailand',
    slug: 'thailand',
    flag: '🇹🇭',
    region: 'Asia',
    investmentRating: 3.9,
    investmentCategory: 'Emerging Market',
    rentalYield: 5.2,
    capitalAppreciation5Y: 3.5,
    priceToRentRatio: 19.2,
    transactionCosts: 5.5,
    propertyTaxRate: 0.02,
    rentalIncomeTax: 15,
    gdpGrowth: 3.8,
    inflationRate: 1.8,
    currencyStability: 0.75,
    populationGrowth: 0.2,
    mortgageAvailability: 'Low',
    foreignOwnershipRestrictions: 'High',
    managementFees: 7,
    maintenanceCosts: 0.8,
    insuranceCosts: 0.3,
    executiveSummary: 'Thailand offers attractive yields in tourist hotspots like Phuket, Pattaya, and Bangkok. Foreign ownership is limited to condominiums, but leasehold structures provide alternatives. The growing digital nomad community supports rental demand.',
    badges: ['Best Rental Yield'],
  },
]

export const pricingTiers: PricingTier[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    description: 'Get started with basic insights',
    features: [
      'Country overviews',
      'Basic metrics',
      'Limited market data',
      'Community access',
    ],
  },
  {
    id: 'single',
    name: 'Per-Country',
    price: 79,
    description: 'Full report for one country',
    features: [
      'Full investment analysis',
      'All 8 report sections',
      'Tax & legal framework',
      'Investment calculator',
      'PDF & Excel download',
      '30-day data updates',
    ],
  },
  {
    id: 'monthly',
    name: 'Monthly',
    price: 99,
    description: 'Unlimited access monthly',
    features: [
      'All countries worldwide',
      'Real-time data updates',
      'Portfolio tracking',
      'Comparison tools',
      'Priority support',
      'Cancel anytime',
    ],
    popular: true,
  },
  {
    id: 'annual',
    name: 'Annual',
    price: 599,
    description: 'Best value for serious investors',
    features: [
      'All monthly features',
      'Premium market insights',
      'API access',
      'Dedicated account manager',
      'Custom report requests',
      'White-label options',
    ],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'Portfolio Manager',
    company: 'Meridian Capital',
    quote: 'Propvest has transformed how we evaluate international property markets. The depth of analysis and clarity of presentation is unmatched in the industry.',
    avatar: '/avatars/sarah.jpg',
  },
  {
    id: '2',
    name: 'Marcus Williams',
    role: 'Private Investor',
    company: 'Independent',
    quote: 'As a first-time international investor, the tax breakdowns and risk assessments gave me confidence to make my first overseas purchase. Highly recommended.',
    avatar: '/avatars/marcus.jpg',
  },
  {
    id: '3',
    name: 'Elena Rodriguez',
    role: 'Real Estate Advisor',
    company: 'Iberia Properties',
    quote: 'We use Propvest reports to brief our clients on market conditions. The data is always current and the methodology is transparent.',
    avatar: '/avatars/elena.jpg',
  },
  {
    id: '4',
    name: 'James Patterson',
    role: 'Family Office Director',
    company: 'Patterson Holdings',
    quote: 'The comparison tools alone are worth the subscription. Being able to evaluate multiple markets side-by-side has streamlined our investment process significantly.',
    avatar: '/avatars/james.jpg',
  },
]

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How often is the data updated?',
    answer: 'Our core market data is updated quarterly, with major economic indicators refreshed monthly. Subscribers to Annual Unlimited receive real-time updates as data becomes available.',
  },
  {
    id: '2',
    question: 'What sources do you use for your analysis?',
    answer: 'We aggregate data from official government statistics, central banks, international organizations (IMF, World Bank), reputable property indices, and on-the-ground research partners in each market.',
  },
  {
    id: '3',
    question: 'Can I get a refund if the report doesn\'t meet my expectations?',
    answer: 'Yes, we offer a 14-day money-back guarantee on all single reports and regional bundles. Annual subscriptions can be canceled within 30 days for a full refund.',
  },
  {
    id: '4',
    question: 'Do you provide investment advice?',
    answer: 'Our reports provide data and analysis to inform your decisions, but we do not provide personalized investment advice. We recommend consulting with qualified financial advisors for specific investment decisions.',
  },
  {
    id: '5',
    question: 'Are the reports available in other languages?',
    answer: 'Currently, all reports are in English. We are working on Spanish, Mandarin, and Arabic translations for release later this year.',
  },
  {
    id: '6',
    question: 'How do I access my purchased reports?',
    answer: 'All purchased reports are immediately available in your dashboard. You can view them online, download as PDF, or export data to Excel format.',
  },
  {
    id: '7',
    question: 'Do you cover commercial real estate?',
    answer: 'Our current focus is residential property investment. Commercial real estate reports are in development and expected to launch in Q3 2026.',
  },
  {
    id: '8',
    question: 'Can I request a report for a country not currently covered?',
    answer: 'Absolutely! Annual Unlimited subscribers can request custom reports for any market. We typically complete new country analyses within 4-6 weeks.',
  },
]

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find(country => country.slug === slug)
}

export function getCountriesByRegion(region: string): Country[] {
  return countries.filter(country => country.region === region)
}

export function getFeaturedCountries(): Country[] {
  return countries.sort((a, b) => b.investmentRating - a.investmentRating).slice(0, 6)
}

export function getTopCountriesByYield(): Country[] {
  return [...countries].sort((a, b) => b.rentalYield - a.rentalYield).slice(0, 3)
}

export function getTopCountriesByGrowth(): Country[] {
  return [...countries].sort((a, b) => b.capitalAppreciation5Y - a.capitalAppreciation5Y).slice(0, 3)
}
